### ISSUE TITLE
Décodeur TTI non aligné

### ISSUE THREAD

**Issue by suytt** [Strega-Technologies/Strega#1]
Bonjour, 
Le décodeur TTI diffère des autres, est-ce une erreur ?

Décodeur Datacake ligne 103 : `var b1 = msg2.substr(2,3);`
Décodeur TTI ligne 148 : `var b1 = msg.substr(1,3);` <-- Différent
Décodeur TTN ligne 148 : `var b1 = msg.substr(2,3);`
Décodeur Chirpstack ligne 103 : `var b1 = msg2.substr(2,3);`

**Comment by Strega-Technologies** [comment]
Nous vérifions et vous revenons rapidement: merci de nous avoir prévenu.

**Comment by Strega-Technologies** [comment]
OK verified and this is normal: the base64 position is different in TTN than in TTI.
Thanks for noticing anyway.
